AWS_ACCESS_KEY_ID = 'aws_access_key_id'
AWS_SECRET_ACCESS_KEY = 'aws_secret_access_key'
TABLE_NAME = 'event_created'
BUCKET_NAME = 'bucket'
CONNECTION = 'host=localhost port=5432 dbname=postgres user=postgres password=postgres'
